# Generated by Django 4.2.13 on 2024-07-12 13:33

import _auth.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('generic', 'Generic User'), ('medical', 'Medical Service User'), ('clinic', 'Clinic User'), ('donor', 'Donor User'), ('blood_bank', 'Blood Bank User'), ('admin', 'Admin User')], default='generic', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMedicaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=200)),
                ('type_etablissement', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('numero_licence', models.CharField(max_length=20)),
                ('numero_enregistrement', models.CharField(max_length=20)),
                ('certificat_enregistrement', models.FileField(upload_to='servicesMedicaux/certificats/')),
                ('profil', models.ImageField(default='images/default.jpg', upload_to=_auth.models.renomer_image)),
                ('groups', models.ManyToManyField(related_name='services_medicaux', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_medical', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(related_name='services_medicaux_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Service Médical',
                'verbose_name_plural': 'Services Médicaux',
            },
        ),
        migrations.CreateModel(
            name='Donneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=10)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('profil', models.ImageField(default='images/default.jpg', upload_to=_auth.models.renomer_image)),
                ('numero_de_donneur', models.CharField(default=_auth.models.numero_de_donneur, max_length=20)),
                ('groups', models.ManyToManyField(related_name='donneurs', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donneur', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(related_name='donneurs_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Donneur',
                'verbose_name_plural': 'Donneurs',
            },
        ),
        migrations.CreateModel(
            name='BanqueDeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('profil', models.ImageField(default='images/default.jpg', upload_to=_auth.models.renomer_image)),
                ('groups', models.ManyToManyField(related_name='banques_de_sang', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banque_de_sang', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(related_name='banques_de_sang_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Banque de Sang',
                'verbose_name_plural': 'Banques de Sang',
            },
        ),
    ]
