# Generated by Django 4.2.13 on 2024-07-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0002_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
