# Generated by Django 6.0.4 on 2026-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0004_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquedesang',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banquedesang',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
