# Generated by Django 6.0.4 on 2026-07-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0005_banquedesang_latitude_banquedesang_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banquedesang',
            options={'ordering': ['-id'], 'verbose_name': 'Banque de Sang', 'verbose_name_plural': 'Banques de Sang'},
        ),
        migrations.AlterModelOptions(
            name='donneur',
            options={'ordering': ['-id'], 'verbose_name': 'Donneur', 'verbose_name_plural': 'Donneurs'},
        ),
        migrations.AlterModelOptions(
            name='servicemedicaux',
            options={'ordering': ['-id'], 'verbose_name': 'Service Médical', 'verbose_name_plural': 'Services Médicaux'},
        ),
    ]
