# Generated by Django 4.2.13 on 2024-07-12 13:33

import bankDeSang.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PocheDeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('date_de_prelevement', models.DateField(default=datetime.date.today)),
                ('type_produit', models.CharField(choices=[('Sang total', 'Sang total'), ('Concentré de globules rouges', 'Concentré de globules rouges'), ('Plasma', 'Plasma'), ('Plaquettes', 'Plaquettes')], max_length=30)),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('date_enregistrement', models.DateField(auto_now=True)),
                ('date_expiration', models.DateField(default=bankDeSang.models.default_date_expiration)),
                ('code_qr', models.ImageField(blank=True, null=True, upload_to=bankDeSang.models.code_qr_poche_de_sang)),
                ('donneur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='_auth.donneur')),
            ],
        ),
        migrations.CreateModel(
            name='StockDeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_poches', models.IntegerField(default=1)),
                ('date_enregistrement', models.DateField(auto_now=True)),
                ('poche_de_sang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankDeSang.pochedesang')),
            ],
        ),
        migrations.CreateModel(
            name='DonDeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_produit', models.CharField(choices=[('Sang total', 'Sang total'), ('Concentré de globules rouges', 'Concentré de globules rouges'), ('Plasma', 'Plasma'), ('Plaquettes', 'Plaquettes')], max_length=30)),
                ('date_don', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField(default=bankDeSang.models.default_date_expiration)),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_auth.donneur')),
                ('poche_de_sang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankDeSang.pochedesang')),
            ],
        ),
    ]
