# Generated by Django 4.2.13 on 2024-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankDeSang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdesang',
            name='groupe_sanguin',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pochedesang',
            name='date_expiration',
            field=models.DateField(),
        ),
    ]
