# Generated by Django 4.2.13 on 2024-07-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankDeSang', '0002_stockdesang_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pochedesang',
            name='est_disponible',
            field=models.BooleanField(default=True),
        ),
    ]
