# Generated by Django 4.2.13 on 2024-07-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankDeSang', '0003_pochedesang_est_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='pochedesang',
            name='en_transition',
            field=models.BooleanField(default=False),
        ),
    ]
