# Generated by Django 4.2.13 on 2024-07-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankDeSang', '0004_pochedesang_en_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdesang',
            name='poche_de_sang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_bankdesang', to='bankDeSang.pochedesang'),
        ),
    ]
