# Generated by Django 4.2.13 on 2024-07-23 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_utilisateur_email'),
        ('bankDeSang', '0005_alter_stockdesang_poche_de_sang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdesang',
            name='poche_de_sang',
        ),
        migrations.AddField(
            model_name='pochedesang',
            name='bank_de_sang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_auth.banquedesang'),
        ),
        migrations.AddField(
            model_name='pochedesang',
            name='service_medicaux',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_auth.servicemedicaux'),
        ),
    ]
