# Generated by Django 6.0.4 on 2026-06-02 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0005_banquedesang_latitude_banquedesang_longitude'),
        ('bankDeSang', '0006_remove_stockdesang_poche_de_sang_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ajout', 'Ajout'), ('modification', 'Modification'), ('suppression', 'Suppression')], max_length=20)),
                ('groupe_sanguin', models.CharField(blank=True, max_length=3, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('banque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historique_stock', to='_auth.banquedesang')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de stock',
                'verbose_name_plural': 'Historiques de stock',
                'ordering': ['-date'],
            },
        ),
    ]
