# Generated by Django 6.0.4 on 2026-07-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankDeSang', '0007_historiquestock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dondesang',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='pochedesang',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stockdesang',
            options={'ordering': ['-id']},
        ),
    ]
