# Generated by Django 6.0.4 on 2026-07-09 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_auth', '0006_alter_banquedesang_options_alter_donneur_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVousDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creneau', models.CharField(choices=[('08:00-10:00', '08:00 - 10:00'), ('10:00-12:00', '10:00 - 12:00'), ('14:00-16:00', '14:00 - 16:00'), ('16:00-18:00', '16:00 - 18:00')], max_length=20)),
                ('statut', models.CharField(choices=[('Planifié', 'Planifié'), ('Annulé', 'Annulé'), ('Effectué', 'Effectué')], default='Planifié', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('banque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_auth.banquedesang')),
                ('donneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='_auth.donneur')),
            ],
            options={
                'verbose_name': 'Rendez-vous de don',
                'verbose_name_plural': 'Rendez-vous de don',
                'ordering': ['date', 'creneau'],
            },
        ),
    ]
