# Generated by Django 4.2.13 on 2024-07-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('date_de_naissance', models.DateField()),
                ('proche', models.CharField(max_length=200)),
                ('relation_proche_patient', models.CharField(blank=True, max_length=200)),
                ('telephone_proche', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeDeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True)),
                ('type_produit', models.CharField(choices=[('Sang total', 'Sang total'), ('Concentré de globules rouges', 'Concentré de globules rouges'), ('Plasma', 'Plasma'), ('Plaquettes', 'Plaquettes')], max_length=30)),
                ('nombre_poches', models.IntegerField(default=1)),
                ('urgence', models.CharField(choices=[('Immédiate', 'Immédiate'), ('24 heures', '24 heures'), ('Non urgent', 'Non urgent')], max_length=20)),
                ('motif', models.CharField(choices=[('Chirurgie', 'Chirurgie'), ('Accident', 'Accident'), ('Maladie', 'Maladie'), ('Autre', 'Autre')], max_length=20)),
                ('etat', models.CharField(choices=[('En attente', 'En attente'), ('Approuvée', 'Approuvée'), ('Rejetée', 'Rejetée'), ('Complétée', 'Complétée')], default='En attente', max_length=20)),
                ('date_demande', models.DateField(auto_now_add=True)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('donneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_auth.donneur')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceMedicaux.patient')),
                ('serviceMedicaux', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_auth.servicemedicaux')),
            ],
            options={
                'verbose_name': 'Demande de Sang',
                'verbose_name_plural': 'Demandes de Sang',
            },
        ),
    ]
