# Generated by Django 4.2.13 on 2024-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceMedicaux', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedesang',
            name='groupe_sanguin',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='demandedesang',
            name='nombre_poches',
            field=models.JSONField(default=dict),
        ),
    ]
