# Generated by Django 4.2.13 on 2024-07-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceMedicaux', '0002_alter_demandedesang_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedesang',
            name='nombre_poches_allouees',
            field=models.JSONField(default=dict),
        ),
    ]
