# Generated by Django 4.2.13 on 2024-07-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_utilisateur_email'),
        ('serviceMedicaux', '0003_demandedesang_nombre_poches_allouees'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='groupe_sanguin',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_auth.utilisateur'),
        ),
    ]
