# Generated by Django 4.2.13 on 2024-07-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('_auth', '0003_utilisateur_email'),
        ('bankDeSang', '0005_alter_stockdesang_poche_de_sang'),
        ('serviceMedicaux', '0004_patient_groupe_sanguin_patient_utilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDeSang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('nombre_de_poches', models.IntegerField(default=1)),
                ('date_enregistrement', models.DateField(auto_now=True)),
                ('poche_de_sang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_servicemedicaux', to='bankDeSang.pochedesang')),
                ('service_medical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_auth.servicemedicaux')),
            ],
        ),
    ]
