# Generated by Django 4.2.13 on 2024-07-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceMedicaux', '0006_stock_de_sang_delete_stockdesang'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedesang',
            name='poches_recues',
            field=models.JSONField(default=dict),
        ),
    ]
