# Generated by Django 4.2.13 on 2024-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceMedicaux', '0007_demandedesang_poches_recues'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedesang',
            name='etat_groupes',
            field=models.JSONField(default=dict),
        ),
    ]
