# Generated by Django 6.0.4 on 2026-07-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceMedicaux', '0008_demandedesang_etat_groupes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandedesang',
            options={'ordering': ['-id'], 'verbose_name': 'Demande de Sang', 'verbose_name_plural': 'Demandes de Sang'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='stock_de_sang',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='demandedesang',
            name='etat',
            field=models.CharField(choices=[('En attente', 'En attente'), ('1/2 Approuvee', '1/2 Approuvee'), ('Approuvee', 'Approuvee'), ('Rejetee', 'Rejetee'), ('Completee', 'Completee')], default='En attente', max_length=20),
        ),
    ]
