# Generated by Django 6.0.4 on 2026-07-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceMedicaux', '0009_alter_demandedesang_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandedesang',
            name='ordonnance_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ordonnances/'),
        ),
    ]
